[settings]
block = 19101579
coinbase = "0x1dd35b4da6534230ff53048f7477f17f7f4e7a70"
multicaller = "0x3dd35b4da6534230ff53048f7477f17f7f4e7a70"

[modules]
price = true
signer = true
encoder = true
arb_path_merger = true
same_path_merger = true
diff_path_merger = true
arb_block = false
arb_mempool = true
flashbots = false

[pools]
a = { address = "0x2dd35b4da6534230ff53048f7477f17f7f4e7a70", class = "uniswap2" }

[txs]
tx_1 = { hash = "0xf9fb98fe76dc5f4e836cdc3d80cd7902150a8609c617064f1447c3980fd6776b", send = "mempool" }

[tokens]
weth = { address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2", symbol = "WETH", decimals = 18, basic = true }

[assertions]
swaps_encoded = 14
swaps_ok = 11
best_profit_eth = 181.37
